version: 1
labels:
  - label: "automerge"
    authors: ["softwaremill-ci"]
    files:
      - "build.sbt"
      - "project/Versions.scala"
  - label: "foo"
    authors: ["micsza"]
  - label: "bar"
    authors: [ "micsza" ]
